version: '3.8'

services:
  auth:
    build:
      context: ./auth
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://db:27017/auth  # URI for Authentication service

  user_profiles:
    build:
      context: ./user_profiles
    ports:
      - '3001:3001'
    environment:
      - MONGO_URI=mongodb://db:27017/profiles  # URI for User Profiles service

  activity_history:
    build:
      context: ./activity_history
    ports:
      - '3002:3002'
    environment:
      - MONGO_URI=mongodb://db:27017/history  # URI for Activity History service

  db:
    image: mongo
    ports:
      - '27017:27017'  # MongoDB service port